name: Cucumber AgileTest Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby environment (Ruby 3.2.4)
      - name: Set up Ruby 3.2.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'

      # Install necessary packages and gems
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install unzip -y
          gem install cucumber
          gem install rspec-expectations

      # Ensure the report directory exists and run Cucumber tests
      - name: Run Cucumber and generate report
        run: |
          mkdir -p report
          cucumber --format json --out report/cucumber_report.json
          ls -la report/
          cat report/cucumber_report.json

      # Authenticate and upload Cucumber results to AgileTest
      - name: Upload Cucumber Results to AgileTest
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          export token=$(curl 'https://agile-test-stg-dot-devsamurai-dev.ue.r.appspot.com/api/apikeys/authenticate' -X POST -H 'Content-Type:application/json' --data '{"clientId":"'"$CLIENT_ID"'","clientSecret":"'"$CLIENT_SECRET"'"}' | tr -d '"')
          echo $token
          curl -X POST -H "Content-Type:application/json" -H "Authorization:JWT $token" --data @report/cucumber_report.json "https://api.dev.agiletest.app/ds/test-executions/cucumber?projectKey=AUT"
          echo "done"