name: Trigger test
run-name: ${{ github.actor }} is testing out GitHub Actions on develop branch 🚀
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      PROJECT_KEY:
        description: The key of project
        type: string
        required: true
      TEST_EXECUTION_KEY:
        description: The key of test execution
        type: string
        required: false

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0' ]
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
         # Set up Ruby environment
     - name: Set up Ruby ${{ matrix.ruby-version }}
       uses: ruby/setup-ruby@v1
       with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      # Install dependencies
     - name: Install dependencies
       run:  apt-get update -qq
     - run :  apt-get install unzip
     - run :  gem install cucumber
     - run :  gem install rspec-expectations

      # Run Cucumber tests
     - name: Run Cucumber
       run: cucumber --format json --out report/cucumber_report.json 
     - run: ls
     - name : import result
       run: export token=$(curl 'https://agile-test-stg-dot-devsamurai-dev.ue.r.appspot.com/api/apikeys/authenticate' -X POST -H 'Content-Type:application/json' --data '{"clientId":"'"$CLIENT_ID"'","clientSecret":"'"$CLIENT_SECRET"'"}' | tr -d '"')
     - run: echo $token
     - run: curl -X POST -H "Content-Type:application/json" -H "Authorization:JWT $token" --data @cucumber_report.json "https://api.dev.agiletest.app/ds/test-executions/cucumber?projectKey=AUT"
    

