name: Test Pipeline

on:
  push:
    branches:
      - junit
  pull_request:
    branches:
      - junit
  workflow_dispatch:
    inputs:
      PROJECT_KEY:
        description: The key of project
        type: string
        required: true # require project key
      TEST_EXECUTION_KEY:
        description: The key of test execution
        type: string
        required: false # optional test execution key
      milestoneId:
        description: The id of milestone
        type: string
        required: false
      testEnvironments:
        description: The list name of test environments
        type: string
        required: false
      testPlanKey: 
        description: The list name of test environments
        type: string
        required: false
      revision: 
        description: The list name of test environments
        type: string
        required: false
      fixVersions: 
        description: The list name of test environments
        type: string
        required: false      
      


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run test & generate report
        run: |
          yarn
          yarn junit-test
      - name: Upload report to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/
      - name: Upload report to AgileTest.App
        env:
          AGILETEST_BASE_URL: ${{ secrets.AGILETEST_BASE_URL }}
          AGILETEST_AUTH_BASE_URL: ${{ secrets.AGILETEST_AUTH_BASE_URL }}
          AGILETEST_CLIENT_ID: ${{ secrets.AGILETEST_CLIENT_ID }}
          AGILETEST_CLIENT_SECRET: ${{ secrets.AGILETEST_CLIENT_SECRET }}
        run: |
          docker run --rm \
          -e AGILETEST_BASE_URL=$AGILETEST_BASE_URL \
          -e AGILETEST_AUTH_BASE_URL=$AGILETEST_AUTH_BASE_URL \
          -e AGILETEST_CLIENT_ID=$AGILETEST_CLIENT_ID \
          -e AGILETEST_CLIENT_SECRET=$AGILETEST_CLIENT_SECRET \
          -v ${{ github.workspace }}/reports:/reports \
          ghcr.io/agiletestapp/agiletest-cli:latest \
          test-execution import --framework-type junit --project-key TC \
          /reports/junit-report.xml

      - name: After Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          # TEST_EXECUTION_KEY: ${{ secrets.TEST_EXECUTION_KEY }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            RESULT="success"
          else
            RESULT="failed"
          fi
          
          echo $RESULT
          echo "Owner/Repo: ${{ github.repository }}"
          echo "Workflow Run ID: ${{ github.run_id }}"

          export token=$(curl 'https://dev.agiletest.atlas.devsamurai.com/api/apikeys/authenticate' -X POST -H 'Content-Type:application/json' --data '{"clientId":"'"$CLIENT_ID"'","clientSecret":"'"$CLIENT_SECRET"'"}' | tr -d '"')
          echo $token
          # Send the result data to the specified endpoint
          curl -H "Content-Type:application/json" -H "Authorization:JWT $token" --data '{ "repository": "'"${{ github.repository }}"'", "runId": "'"${{ github.run_id }}"'", "tool":"github", "result":"'"$RESULT"'"  }' "https://dev.agiletest.atlas.devsamurai.com/ds/test-executions/${{ inputs.TEST_EXECUTION_KEY }}/pipeline/history?projectKey=${{ inputs.PROJECT_KEY }}"