name: Test Pipeline

on:
  push:
    branches:
      - junit
  pull_request:
    branches:
      - junit

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: update result
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          export token=$(curl 'https://dev.agiletest.atlas.devsamurai.com/api/apikeys/authenticate' -X POST -H 'Content-Type:application/json' --data '{"clientId":"'"$CLIENT_ID"'","clientSecret":"'"$CLIENT_SECRET"'"}' | tr -d '"')
          echo $token
          curl -X POST -H "Content-Type:application/xml" -H "Authorization:JWT $token" --data @"./playwright-report/results.xml" "https://dev.api.agiletest.app/ds/test-executions/junit?projectKey=AUT&testExecutionKey=${testExecutionKey}"
          echo "done"

          
            - if [ "$BITBUCKET_EXIT_CODE" -eq 0 ]; then
              RESULT="SUCCESS";
              else
              RESULT="FAILED";
              fi
            - |
              export token=$(curl -H "Content-Type: application/json" -X POST --data '{ "clientId": "'"$CLIENT_ID"'", "clientSecret": "'"$CLIENT_SECRET"'" }' https://dev.agiletest.atlas.devsamurai.com/api/apikeys/authenticate | tr -d '"')
            - |
              curl -H "Content-Type: application/json" -H "Authorization: JWT $token" --data '{ "buildNumber": "'"$BITBUCKET_BUILD_NUMBER"'", "tool": "'"bitbucket"'", "repoSlug": "'"$BITBUCKET_REPO_SLUG"'", "workspace": "'"$BITBUCKET_WORKSPACE"'", "result": "'"$RESULT"'"  }' "https://dev.api.agiletest.app/ds/test-executions/$TEST_EXECUTION_KEY/pipeline/history?projectKey=$PROJECT_KEY"