name: Test Pipeline

on:
  push:
    branches:
      - junit
  pull_request:
    branches:
      - junit

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Get API token
        run: |
          token=$(curl 'https://agile-test-stg-dot-devsamurai-dev.ue.r.appspot.com/api/apikeys/authenticate' \
            -X POST \
            -H 'Content-Type:application/json' \
            --data '{"clientId":"'"$CLIENT_ID"'","clientSecret":"'"$CLIENT_SECRET"'"}' | tr -d '"')
          echo $token
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Upload test results
        run: |
          curl -X POST -H "Content-Type:application/xml" \
            -H "Authorization:JWT $token" \
            --data @"./playwright-report/results.xml" \
            "https://api.dev.agiletest.app/ds/test-executions/junit?projectKey=AUT"
          
      - name: Job done
        run: echo "done"